### ISSUE TITLE
source

### ISSUE THREAD

**Issue by sascha-schwegelbauer** [mayur-tendulkar/TranslateIT#1]
Hi Mayur,

in your recent blogpost on xamarin (mentioned in the newsletter yesterday, the post itself was posted october, 10th - https://blog.xamarin.com/build-and-release-five-star-apps-faster-with-visual-studio-mobile-center/), you mentioned the "TranslateIT" app and it's sourcecode in this repository.
Unfortunately, I cannot find anything except a blank app.
Could you check this please?

Thanks,
Sascha

**Comment by mayur-tendulkar** [comment]
Hello Sascha,

Sorry for the trouble. This repo was initially in VSTS. I've just moved the files over here while deleting old project. Please download and test the code. Let me know if it still needs any fixes.
